@url = http://localhost:3035

### simple users READ
GET {{url}}/simple_users
content-type: application/json

### simple users CREATE
POST {{url}}/simple_users/create
content-type: application/json
	
{
	"firstName": "Andre",
	"lastName": "Creationer"
}

### simple users UPDATE
PATCH {{url}}/simple_users/update/619e56b9258e42a3f346e668 
content-type: application/json
	
{
	"lastName": "Scissorhands"
}

### simple users DELETE
DELETE {{url}}/simple_users/delete/619e0fd0d36a01811ea3bfa1
content-type: application/json

### nested users READ
GET {{url}}/nested_users
content-type: application/json

### nested users READ
GET {{url}}/nested_users/emails
content-type: application/json

### nested users READ
GET {{url}}/nested_users/accountHistory/619d7bb7017e9300920ffb78
content-type: application/json

### nested users CREATE
POST {{url}}/nested_users/create
content-type: application/json
	
{
	"name" : "Stephanie Added888",
	"username" : "Brandyn_Reilly59",
	"email" : "Tyshawn.Abshire@yahoo.com",
	"address" : {
		"street" : "Hill Parks",
		"suite" : "Suite 582",
		"city" : "Garfieldmouth",
		"zipcode" : "21401-7727"
	},
	"phone" : "502-899-9440 x015",
	"website" : "jessyca.org",
	"company" : "Kshlerin, Wiza and Ferry",
	"accountHistory" : [
		{
			"amount" : 333,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Fantastic Wooden Table"
		},
		{
			"amount" : 665.01,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Tasty Soft Towels"
		},
		{
			"amount" : 205.68,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Small Concrete Chair"
		}
	]
}

### nested users CREATE WITH VALIDATION ERROR
POST {{url}}/nested_users/create
content-type: application/json
	
{
	"name_BAD" : "Stephanie Added",
	"username" : "Brandyn_Reilly59",
	"email" : "Tyshawn.Abshire@yahoo.com",
	"address" : {
		"street" : "Hill Parks",
		"suite" : "Suite 582",
		"city" : "Garfieldmouth",
		"zipcode" : "21401-7727"
	},
	"phone" : "502-899-9440 x015",
	"website" : "jessyca.org",
	"company" : "Kshlerin, Wiza and Ferry",
	"accountHistory" : [
		{
			"amount" : 333,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Fantastic Wooden Table"
		},
		{
			"amount" : 665.01,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Tasty Soft Towels"
		},
		{
			"amount" : 205.68,
			"date" : "2021-11-15T16:52:26.505+01:00",
			"purchase" : "Small Concrete Chair"
		}
	]
}

### nested users UPDATE
PATCH {{url}}/nested_users/update/619d7bb7017e9300920ffb78
content-type: application/json
	
{
	"name": "Steven CHANGED",
	"address.street": "changed street",
	"accountHistory.2.amount": 999
}

### nested users DELETE
POST {{url}}/nested_users/delete/619d7bb7017e9300920ffbda
content-type: application/json